library(Hmisc)
library(lattice)
Allpara<-cbind(members$numLogins,members$numForumPosts ,members$numMsgUser,members$convRequests,members$forumViews,members$helpViews,members$pageViewsWeb, members$pageViewsApp, members$activedays)
Allpara_nazero<- Allpara[ apply(Allpara!=0, 1, any), , drop=FALSE] 
rcorr(Allpara_nazero, type="pearson")
apply(Allpara_nazero, 2, var)
histogram(Allpara)
hist(Allpara_nazero)
plot(Allpara_nazero[,1], xlab = 'Sample quantiles of account login', ylab = '', main = 'Empirical Cumluative Distribution')
plot(Allpara_nazero[,2], xlab = 'Sample quantiles', ylab = '', main = 'Empirical Cumluative Distribution')
plot(Allpara_nazero[,3], xlab = 'Sample quantiles', ylab = '', main = 'Empirical Cumluative Distribution')
plot(Allpara_nazero[,4], xlab = 'Sample quantiles', ylab = '', main = 'Empirical Cumluative Distribution')
plot(Allpara_nazero[,5], xlab = 'Sample quantiles', ylab = '', main = 'Empirical Cumluative Distribution')
plot(Allpara_nazero[,6], xlab = 'Sample quantiles', ylab = '', main = 'Empirical Cumluative Distribution')
plot(Allpara_nazero[,7], xlab = 'Sample quantiles', ylab = '', main = 'Empirical Cumluative Distribution')
plot(Allpara_nazero[,8], xlab = 'Sample quantiles', ylab = '', main = 'Empirical Cumluative Distribution')
plot(Allpara_nazero[,9], xlab = 'Sample quantiles', ylab = '', main = 'Empirical Cumluative Distribution')
vector1 <- c(1225.16825,67.69169,530294.17569,322.54270,13740.66195,106.17023,3093.61783,3056.26803,822.13376)
((vector1-vector1[1])/vector1[1])*100
